server:
  port: 8080

spring:
  application:
    name: tourni-gateway
  
  config:
    import: optional:configserver:http://${CONFIG_SERVICE_HOST:localhost}:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Identity Service - Public (no authentication required)
        - id: tourni-identity-service
          uri: lb://tourni-identity-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: RoleBasedAuthorizationFilter  # No roles required - public access
        
        # Management Service - USER and ADMIN access for read operations
        - id: tourni-management-read
          uri: lb://tourni-management
          predicates:
            - Path=/api/v1/manage/**
            - Method=GET
          filters:
            - name: RoleBasedAuthorizationFilter
              args:
                requiredRoles: USER,ADMIN
        
        # Management Service - ADMIN only for write operations
        - id: tourni-management-write
          uri: lb://tourni-management
          predicates:
            - Path=/api/v1/manage/**
            - Method=POST,PUT,DELETE,PATCH
          filters:
            - name: RoleBasedAuthorizationFilter
              args:
                requiredRoles: ADMIN
        
        # AI Service - Authenticated users only
        - id: tourni-ai
          uri: lb://tourni-ai
          predicates:
            - Path=/api/v1/ai/**
          filters:
            - name: RoleBasedAuthorizationFilter
              args:
                requiredRoles: USER,ADMIN
        
        # Eureka Discovery - ADMIN only
        - id: tourni-discovery-service
          uri: http://${EUREKA_HOST:tourni-discovery-service}:${EUREKA_PORT:8761}
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
            - name: RoleBasedAuthorizationFilter
              args:
                requiredRoles: ADMIN
        
        - id: tourni-discovery-service-static
          uri: http://${EUREKA_HOST:tourni-discovery-service}:${EUREKA_PORT:8761}
          predicates:
            - Path=/eureka/**
          filters:
            - name: RoleBasedAuthorizationFilter
              args:
                requiredRoles: ADMIN


management:
  endpoint:
    gateway:
      enabled: true


