version: '3.7'

services:
  tourni-mysql:
    container_name: tourni-mysql
    image: mysql:8.0.13
    environment:
      MYSQL_ROOT_PASSWORD: Raju@4789
      MYSQL_DATABASE: tournament_db
      MYSQL_USER: tournament_admin
      MYSQL_PASSWORD: tournament@2023
    ports:
      - "3306:3306"
    volumes:
      - mysql-database-data-volume:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: always
    networks:
      - tourni-network

  tempo:
    image: grafana/tempo
    container_name: tempo
    extra_hosts: ['host.docker.internal:host-gateway']
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo-local.yaml:/etc/tempo.yaml:ro
      - ./tempo-data:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "9411:9411" # zipkin
    networks:
      - tourni-network

  loki:
    image: grafana/loki
    container_name: loki
    extra_hosts: ['host.docker.internal:host-gateway']
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"                                   # loki needs to be exposed so it receives logs
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    networks:
      - tourni-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    extra_hosts: ['host.docker.internal:host-gateway']
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - tourni-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    extra_hosts: ['host.docker.internal:host-gateway']
    volumes:
      - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    networks:
      - tourni-network

  tourni-discovery-service:
    image: raju5800/tourni-discovery-service:latest
    container_name: tourni-discovery-service
    ports:
      - "8761:8761"
    depends_on:
      - tourni-config-server
      - prometheus
      - loki
      - tempo
      - grafana
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://tourni-discovery-service:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      CONFIG_SERVICE_HOST: tourni-config-server
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://tempo:9411/api/v2/spans
    networks:
      - tourni-network

  tourni-config-server:
    image: raju5800/tourni-config-server:latest
    container_name: tourni-config-server
    ports:
      - "8888:8888"
    networks:
      - tourni-network
    depends_on:
      - prometheus
      - loki
      - tempo
      - grafana

  tourni-gateway:
    image: raju5800/tourni-gateway:latest
    container_name: tourni-gateway
    ports:
      - "8080:8080"
      - "8089:8089"
    depends_on:
      - tourni-discovery-service
      - tourni-config-server
      - prometheus
      - loki
      - tempo
      - grafana
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://tourni-discovery-service:8761/eureka/
      EUREKA.CLIENT.FETCH-REGISTRY: true
      CONFIG_SERVICE_HOST: tourni-config-server
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://tempo:9411/api/v2/spans
    networks:
      - tourni-network

  tourni-identity-service:
    image: raju5800/tourni-identity-service:latest
    container_name: tourni-identity-service
    ports:
      - "8082:8080"
    depends_on:
      - tourni-mysql
      - tourni-discovery-service
      - tourni-config-server
      - prometheus
      - loki
      - tempo
      - grafana
    environment:
      MYSQL_HOST: tourni-mysql
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: Raju@4789
      MYSQL_DATABASE: tournament_db
      MYSQL_USER: tournament_admin
      MYSQL_PASSWORD: tournament@2023
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://tourni-discovery-service:8761/eureka
      EUREKA.CLIENT.FETCH-REGISTRY: true
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://tempo:9411/api/v2/spans
      CONFIG_SERVICE_HOST: tourni-config-server
    networks:
      - tourni-network

  tourni-management:
    image: raju5800/tourni-management:latest
    container_name: tourni-management
    ports:
      - "8083:8080"
    depends_on:
      - tourni-mysql
      - tourni-discovery-service
      - tourni-identity-service
      - tourni-config-server
      - prometheus
      - loki
      - tempo
      - grafana
    environment:
      MYSQL_HOST: tourni-mysql
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: Raju@4789
      MYSQL_DATABASE: tournament_db
      MYSQL_USER: tournament_admin
      MYSQL_PASSWORD: tournament@2023
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://tourni-discovery-service:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://tempo:9411/api/v2/spans
      EUREKA.CLIENT.FETCH-REGISTRY: true
      CONFIG_SERVICE_HOST: tourni-config-server
    networks:
      - tourni-network

  tourni-ai:
    image: raju5800/tourni-ai:latest
    container_name: tourni-ai
    ports:
      - "8084:8080"
    depends_on:
      - tourni-mysql
      - tourni-discovery-service
      - tourni-config-server
      - prometheus
      - loki
      - tempo
      - grafana
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://tourni-mysql:3306/tournament_db
      MYSQL_HOST: tourni-mysql
      MYSQL_PORT: 3306
      SPRING_DATASOURCE_USERNAME: tournament_admin
      SPRING_DATASOURCE_PASSWORD: tournament@2023
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://tourni-discovery-service:8761/eureka
      CONFIG_SERVICE_HOST: tourni-config-server
    networks:
      - tourni-network

  tourni-ui:
    image: raju5800/tourni-ui:latest
    container_name: tourni-ui
    ports:
      - "8002:8000"
    depends_on:
      - tourni-gateway
    networks:
      - tourni-network

# Volumes
volumes:
  mysql-database-data-volume:

# Networks
networks:
  tourni-network:
    driver: bridge
