eureka:
  client:
    service-url:
      defaultZone: http://tourni-discovery-service:8761/eureka/

spring:
  application:
    name: tourni-ai
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:tourni-mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:tournament_db}
    username: ${MYSQL_USER:tournament_admin}
    password: ${MYSQL_PASSWORD:tournament@2023}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]'