server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://tourni-discovery-service:8761/eureka/

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://tourni-mysql:3307/tournament_db
        username: tournament_admin
        password: tournament@2023

