# tourni-management/application.yml
# LOCAL BOOTSTRAP CONFIG ONLY
# All other configuration is managed in: https://github.com/raju4789/tourni-config
# - tourni-management.yml (base config for all environments)
# - tourni-management-{profile}.yml (environment-specific overrides)

server:
  port: 8083  # Service port (not externalized, needs to be known before config server loads)

spring:
  application:
    name: tourni-management  # Service name for Eureka registration
  
  config:
    # Import external configuration from Config Server
    # "optional:" = don't fail if config server is unavailable (use defaults)
    import: "optional:configserver:http://${CONFIG_SERVICE_HOST:localhost}:8888"

# NOTE: All other configuration (database, JPA, logging, etc.) is loaded from Config Server
# See: https://github.com/raju4789/tourni-config
