spring:
  application:
    name: tourni-management
  config:
    import: configserver:http://${CONFIG_SERVICE_HOST:localhost}:8888

server:
  port: 0

management:
  observations:
    key-values:
      application: tourni-management
