spring:
  application:
    name: tourni-discovery-service

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "metrics", "prometheus"]
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


  logging:
    pattern:
      level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

