spring:
  application:
    name: tourni-discovery-service
  config:
    import: configserver:http://${CONFIG_SERVICE_HOST:localhost}:8888

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

