spring:
  application:
    name: tourni-discovery-server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      show-details: always


logging:
  pattern:
    level: '%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]'
