spring:
  application:
    name: tourni-discovery-server

server:
  port: 8761

eureka:
  instance:
    hostname: tourni-discovery-server
  client:
    register-with-eureka: false
    fetch-registry: false
