global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'tourni-config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['tourni-config-server:8888']
        labels:
          application: 'Tourni Config Server'

  - job_name: 'tourni-identity-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['tourni-identity-service:8082']
        labels:
          application: 'Tourni Identity Service'

  - job_name: 'tourni-management'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['tourni-management:8083']
        labels:
          application: 'Tourni Management Service'

  - job_name: 'tourni-ai'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['tourni-ai:8084']
        labels:
          application: 'Tourni AI Service'

  - job_name: 'tourni-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['tourni-gateway:8080']
        labels:
          application: 'Tourni Gateway'

  - job_name: 'tourni-mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']
        labels:
          application: 'Tourni MySQL Exporter'
