# docker/common-config.yml
services:
  tourni-deploy-service:
    networks:
      - tourni-network

  tourni-base-config:
    extends:
      service: tourni-deploy-service
    environment:
      MYSQL_HOST: tourni-mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: tournament_db
      MYSQL_USER: tournament_admin
      MYSQL_PASSWORD: tournament@2023
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://tourni-discovery-service:8761/eureka/
      CONFIG_SERVICE_HOST: tourni-config-server
