spring:
    application:
        name: tourni-config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/raju4789/tourni-config

server:
    port: 8888