server:
  port: 8087

spring:
  application:
    name: tourni-identity-service
  config:
    import: configserver:http://${CONFIG_SERVICE_HOST:localhost}:8888

management:
  observations:
    key-values:
      application: tourni-management